### PR TITLE
Basic GUI support

### PR DESCRIPTION
**Pull request by hecrj**
[Demo](https://gfycat.com/livelyonlyhypacrosaurus)
_[Watch in higher quality](https://gfycat.com/livelyonlyhypacrosaurus)_ | _[Code](https://github.com/hecrj/coffee/blob/feature/ui/examples/ui.rs)_

This PR implements a basic UI runtime and integrates it with Coffee.

# Features / Goals
  * Responsive UI layout based on flexbox, built on top of [`stretch`](https://github.com/vislyhq/stretch).
  * Generic `Widget` trait with a `Renderer` associated type, allowing users to build their own custom widgets and UI renderers.
  * Type-safety. No weak references.
  * Simple design, heavily inspired by [Elm](https://elm-lang.org/) and [`elm-ui`](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/). Users define a function describing their UI layout. The resulting UI produces messages on user interaction. Produced messages are processed by another user-defined function, changing state as desired.
  * Simple integration. GUI can easily be added by simply extending your `Game` with the `UserInterface` trait.

# Built-in widgets
  * [x] Column
  * [x] Row
  * [x] Text
  * [x] Button
  * [x] Checkbox
  * [x] Radio button
  * [x] Slider
  * [ ] Progress bar

# Example
This branch includes [an example that showcases all the built-in widgets so far](https://gfycat.com/livelyonlyhypacrosaurus) ([code](https://github.com/hecrj/coffee/blob/feature/ui/examples/ui.rs)). If you want to check it out simply run:

```
cargo run --example ui --features opengl,debug --release
```

# Limitations
This is a first iteration. The current implementation is still missing some basic features like:

  * Text input widget. This is a pretty complex widget if we want to do it well. We may need to contribute to `glyph_brush` a bit more.
  * Clipping (no scrollables yet). I have a mental roadmap for this. It involves changing `Target` and the rendering pipelines a bit. I need to further investigate, but it should be doable.
  * Global scaling. I have some ideas for this too (somewhat related to #6), but I think we should probably focus on other stuff first.

Also, there is no way to overlay elements as of now and there are probably many performance optimizations that we could make. However, I would like to wait a bit and gather use cases before implementing these.

# Breaking changes
This PR contains breaking changes that affect the architecture of the engine for the better:

  * The `View` associated type has been removed. Thus, implementors of the `Game` trait are also meant to hold the game assets. This simplifies the API considerably, and it helps model your game state-view relationship with precision, avoiding inconsistencies.
  * The `Game::Input` associated type now has to implement the new `Input` trait. This splits code quite nicely, as the `on_input` method moves away from `Game`. It also makes `Input` implementors reusable. For instance, a `KeyboardAndMouse` type has been implemented that can be used out of the box!
  * The `Game::LoadingScreen` associated type has been introduced. Given that all the `Game` associated types implement a trait with a `load` method, wiring a loading screen now is as simple as writing its name. Because of this, the `Game::new` method is no longer necessary and it is dropped.

# Additional implemented features
  * `Text` alignment, using `HorizontalAlignment` and `VerticalAlignment`
  * `Font::measure`, which allows to measure any `Text`
  * `Rectangle::contains`, returns whether or not it contains the given `Point`
  * `Sprite::scale`
  * `Default` implementation for `Sprite`

# Pending work
  * [x] Rename `UserInterface::Event` to `UserInterface::Message`
  * [x] Move runtime concepts and customization into a (public) module inside `ui`
  * [x] Expose simple concepts using the basic renderer directly on the `ui` module
  * [ ] Implement `ProgressBar` widget
  * [ ] Debug some weird `stretch` behavior (maybe contact maintainers and/or open an issue)
  * [ ] Debug `glyph_brush` measuring functions (they seem to be off)
  * [x] Rethink alignment API
  * [x] Support renderer configuration
  * [x] Control event propagation
  * [x] Remove debug code (maybe split it into another renderer)
  * [x] Update examples
  * [x] Review API consistency
  * [x] Give proper credits ([Kenney](https://kenney.nl) and `stretch`)
  * [x] Update documentation
  * [x] Update `README`
  * [x] Update `CHANGELOG`

### CODE REVIEW

**Comment by PvdBerg1998** [comment]
Perhaps `KeyboardAndMouse::clicks` should return `&[Point]` instead of `&Vec<Point>`? Great project by the way, excited to give it a try when this PR is finished!

**Comment by hecrj** [comment]
@PvdBerg1998 Indeed! Thank you for taking a look and your kind words!

**Comment by hecrj** [comment]
I have uploaded the new docs here: http://coffee-rs.surge.sh/coffee/index.html

I am quite happy with how it's turning out. Any feedback is appreciated!

**Comment by hecrj** [comment]
There is still some work to be done: debugging some weird behavior and implementing a `ProgressBar` widget. However, this PR is already almost as big as the entire engine in `master`... :sweat_smile: 

I think we should open issues so we can properly track the remaining work and deal with them in separate PRs.

So, let's merge this! :tada:

**Comment by PvdBerg1998** [comment]
I think you forgot to document the removal of `State` in the changelog

**Comment by hecrj** [comment]
@PvdBerg1998 `State` was added in this PR, it doesn't exist in the current release. The actual change you may be referring to is the removal of the `View` associated type, which I think I have added to the changelog under the "Changed" section.

In any case, we will review/rewrite the changelog a bit before releasing `0.3.0`.

**Comment by PvdBerg1998** [comment]
No sorry, I didn't see it was only added in this PR. Nice work! 🎉

**Pull request merged**
